test01_db_manager:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "test01"

test02_db_manager:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "test02"
