env: test

http_server:
  port: 8080

consul_net_cfg:
  consul_addr: "127.0.0.1:8500"
  consul_key: "config/svc01/test.yaml"
  config_type: "yaml"
  reload_time: 10

consul_agent_addr: "127.0.0.1:8500"

logger:
  level: debug
  output_to_file:
    enable: false
    path: ""
    with_buffer: false

log_http_info:
  log_request_body: true
  log_response_body: true

biz01:
  field01: "value01"
  field02: "value02"

biz02:
  field01: "value01"
  field02: "value02"

test01_client:
  agent_addr: "127.0.0.1:8500"
  service_name: "test01"
  tag: "test"

test02_client:
  agent_addr: "127.0.0.1:8500"
  service_name: "test02"
  tag: "test"
