env: test

rpc_server:
  port: 8081
  register_entries:
    - service_name: "test01"
      tags: ["test"]
    - service_name: "test02"
      tags: ["test"]

consul_agent_addr: "127.0.0.1:8500"

logger:
  level: debug
  output_to_file:
    enable: false
    path: ""
    with_buffer: false
