env: test

rpc_server:
  port: 8081
  services:
    - service_name: "test01"
      tags: ["test"]
    - service_name: "test02"
      tags: ["test"]

logger:
  level: debug
  output_to_file:
    enable: false
    path: ""
    with_buffer: false
