env: live

http_server:
  port: 8080

logger:
  level: info
  output_to_file:
    enable: true
    path:
    with_buffer: false

log_http_info:
  log_request_body: true
  log_response_body: true

biz01:
  field01: "value01"
  field02: "value02"

biz02:
  field01: "value01"
  field02: "value02"
